FROM public.ecr.aws/lambda/python:3.11-arm64

ENV MODEL_PATH=/${LAMBDA_TASK_ROOT}/model.tflite

RUN pip install poetry

COPY poetry.lock pyproject.toml ${LAMBDA_TASK_ROOT}

RUN poetry config virtualenvs.create false
RUN poetry install --without dev

COPY predict.py model.tflite ${LAMBDA_TASK_ROOT}
# COPY /static ${LAMBDA_TASK÷_ROOT}/static

CMD [ "predict.lambda_handler" ]
